version: '3'

networks:
  local:

volumes:
  postgres-db:
  db:
    driver: local

services:

  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_DB=beers_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser123
    volumes:
      - ./infrastructure/local/provision/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      local:
        aliases:
          - postgres_beers_api

  beers_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - pipenv_dev=1
    depends_on:
      - "postgres"
    links:
      - postgres:postgres
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PIPENV_DOTENV_LOCATION=/tmp/.env
    working_dir: /code
    volumes:
      - ./beers_api:/code
      - ./.env:/tmp/.env
    command: bash -c "
      dockerize -wait tcp://postgres_beers_api:5432 -timeout 1m &&
      pipenv run python manage.py migrate &&
      pipenv run gunicorn --name app --workers 2 --log-level debug --error-logfile /tmp/gunicorn_err.log --reload --bind 0.0.0.0:9999 beers_api.wsgi:application
      "
    ports:
      - 9999:9999
    networks:
      local:
